wandb_version: 1

activation_function:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 100
drop_out:
  desc: null
  value: 1.0
elapsed_time:
  desc: null
  value: 774.892026424408
epoch:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.005
num_input:
  desc: null
  value: 28
num_output:
  desc: null
  value: 6
